#!/bin/bash

#which clipboard to use, valid options are "primary" and "clipboard"
SELECTION=clipboard
#choose your terminal
TERM=sakura
shopt -s lastpipe

ops=(
    w3m
    mpv
    MPV
    youtube-dl
    YOUTUBE_DL
    transmission
    curl-download
    curl-save
    wget-saveall
    add-bookmark
)

uselariza() {

# to use with rofi ##
option=$(for i in "${ops[@]}"; do echo "$i"; done |  rofi -dmenu -location 1 -l 10 -width 100 -p : -font "Inconsolata 14" -mesg "open <u>$1</u> with...")
## uncomment below line to use with dmenu , and comment out line before this ##
# option=$(for i in "${ops[@]}"; do echo "$i"; done | /usr/bin/dmenu -b )

[[ ! $option ]] && exit

case "$option" in

w3m) $TERM -e w3m "$1" ;;
mpv) $TERM -e w3mpv "$1" ;;
MPV) $TERM -e mpv "$1"  ;;
youtube-dl) $TERM -e w3ytdl "$1" ;;
YOUTUBE-DL) $TERM -e youtube-dl "$1" ;;
## download torrent using transmission-cli
transmission) $TERM -e transmission-remote-cli "$1" ;;
## downlod with curl in current dir (home)
curl-download) $TERM -e curl -L -O --user-agent Mozilla/5.0 "$1" ;;
## save page as curl.html in Downloads
curl-save) $TERM -e curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 "$1" ;;
## save full page with wget, saved in Downloads
wget-saveall) $TERM -e wget --user-agent=Mozilla/5.0 --mirror -p --convert-links -P ~/Downloads "$1" ;;
# add bookmark
add-bookmark) 
	    echo -e "news\nlinux\ncycling\nsocial\nshopping\ntravel" | rofi -dmenu -location 1 -l 6 -width 100 -p : -font "Inconsolata 14" -mesg "choose tag for bookmark" | read tag
	    ## uncomment below for use with dmenu and comment out the upper line ##
	    # echo -e "news\nlinux\ncycling\nsocial\nshopping\ntravel" | /usr/bin/dmenu -fn "Inconsolata 14" -p "choose tag" | read tag
	    echo "$1 $tag" >> ~/.config/lariza/bookmarks ;; 
## use any other external program with !chromium or !firefox or ?firefox etc.
*) $option "$1" ;;
esac
}

getopts u: name
case $name in
u) uselariza $OPTARG ;;
*) uselariza "$(xclip -o -selection $SELECTION)" ;;
esac
