#!/bin/bash

#which clipboard to use, valid options are "primary" and "clipboard"
SELECTION=clipboard
#choose your terminal
TERM=sakura
shopt -s lastpipe
#ROFI='rofi -dmenu -location 1 -l 9 -width 100 -p OPEN_WITH:'
ROFI='/usr/bin/dmenu -b'

echo -e "chromium\nw3m\nmpv\nMPV\nyoutube-dl\nYOUTUBE-DL\ntransmission\ncurl-download\ncurl-save\nwget-saveall" | $ROFI | read "option"

uselariza() {
case "$option" in

w3m) $TERM -e w3m "$1" ;;
mpv) $TERM -e w3mpv "$1" ;;
MPV) $TERM -e mpv "$1"  ;;
youtube-dl) $TERM -e w3ytdl "$1" ;;
YOUTUBE-DL) $TERM -e youtube-dl "$1" ;;
## download torrent using transmission-cli
transmission) $TERM -e transmission-remote-cli "$1" ;;
## downlod with curl in current dir (home)
curl-download) $TERM -e curl -L -O --user-agent Mozilla/5.0 "$1" ;;
## save page as curl.html in Downloads
curl-save) $TERM -e curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 "$1" ;;
## save full page with wget, saved in Downloads
wget-saveall) $TERM -e wget --user-agent=Mozilla/5.0 --mirror -p --convert-links -P ~/Downloads "$1" ;;
## use any other external program with !chromium or !firefox or ?firefox etc.
*) $option "$1" ;;
esac
}

useclipboard() {
case "$option" in

w3m) $TERM -e w3m "$(xclip -o -selection $SELECTION)" ;;
mpv) $TERM -e w3mpv "$(xclip -o -selection $SELECTION)" ;;
MPV) $TERM -e mpv "$(xclip -o -selection $SELECTION)"  ;;
youtube-dl) $TERM -e w3ytdl "$(xclip -o -selection $SELECTION)" ;;
YOUTUBE-DL) $TERM -e youtube-dl "$(xclip -o -selection $SELECTION)" ;;
## download torrent using transmission-cli
transmission) $TERM -e transmission-remote-cli "$(xclip -o -selection $SELECTION)" ;;
## downlod with curl in current dir (home)
curl-download) $TERM -e curl -L -O --user-agent Mozilla/5.0 "$(xclip -o -selection $SELECTION)" ;;
## save page as curl.html in Downloads
curl-save) $TERM -e curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 "$(xclip -o -selection $SELECTION)" ;;
## save full page with wget, saved in Downloads
wget-saveall) $TERM -e wget --user-agent=Mozilla/5.0 --mirror -p --convert-links -P ~/Downloads "$(xclip -o -selection $SELECTION)" ;;
## use any other external program with !chromium or !firefox or ?firefox etc.
*) $option "$(xclip -o -selection $SELECTION)" ;;
esac
}

case "$1" in
"-u")  uselariza $2 ;;
*) useclipboard ;;
esac
