#!/bin/bash

#which clipboard to use, valid options are "primary" and "clipboard"
SELECTION=clipboard
# choose bookmarks file location
BOOKMARKS="$HOME/.config/vimb/bookmark"
#choose your terminal
TERM=termite
shopt -s lastpipe

ops=(
    qutebrowser
    mpv
    video-play-download
#    curl-download
#    curl-save
    send_to_kodi
    aria2
    wget
    add-bookmark
    w3m
    transmission
    def
    guj
    netsurf
)

getopts u: name
case $name in
u) url=$OPTARG ;;
*) url="$(xclip -o -selection $SELECTION)" ;;
#lariza "$(xclip -o -selection $SELECTION)" && exit ;;
#url="$(xclip -o -selection $SELECTION)" ;;
esac

[[ ! $url ]] && exit
# to use with rofi ##
option=$(for i in "${ops[@]}"; do echo "$i"; done |  rofi -dmenu -location 1 -l 10 -width 100 -p : -font "Inconsolata 14" -mesg "open <u>$url</u> with...")
## uncomment below line to use with dmenu , and comment out line before this ##
# option=$(for i in "${ops[@]}"; do echo "$i"; done | /usr/bin/dmenu -b )

[[ ! $option ]] && exit

case "$option" in

w3m) $TERM -e "w3m $url" ;;
news) vimb -p news "$url" ;;
mpv) $TERM --class=TERM -e "mpv --no-resume-playback --ytdl-format=18/43/best $url" ;;
vlc) $TERM --class=TERM -e "cvlc $url" ;;
video-play-download) $TERM --class=TERM -e "hotstar $url" ;;
## download torrent using transmission-cli
#aria2) export DIANA_SECRET_TOKEN=tejashwi; export DIANA_HOST=docstore; diana add "$url" ;;
aria2) aria2c --dir=/home/sharad/Downloads/aria2 --log=/home/sharad/Downloads/aria2/aria2.log --no-conf "$url" ;;
transmission) transmission-remote-cli -c docstore:9091 "$url" ;;
## downlod with curl in current dir (home)
curl-download) $TERM -e "curl -g -L -J -O --user-agent Mozilla/5.0 $url" ;;
## save page as curl.html in Downloads
curl-save) $TERM -e "curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 $url" ;;
## save full page with wget, saved in Downloads
wget) $TERM --class=wget -e "wget --user-agent=Mozilla/5.0 --mirror -P $HOME/Downloads $url" ;;
# add bookmark
add-bookmark) 
	    echo -e "news\nlinux\ncycling\nsocial\nshopping\ntravel" | rofi -dmenu -location 1 -l 6 -width 100 -p : -font "Inconsolata 14" -mesg "choose tag for bookmark" | read tag
	    ## uncomment below for use with dmenu and comment out the upper line ##
	    # echo -e "news\nlinux\ncycling\nsocial\nshopping\ntravel\nmotors" | /usr/bin/dmenu -fn "Inconsolata 14" -p "choose tag" | read tag
	    echo "$url $tag" >> $BOOKMARKS ;; 
## use any other external program with !chromium or !firefox or ?firefox etc.
def) notify-send "$( sdcv -n --data-dir ~/dic/english/ $url )" && exit ;;
guj) notify-send "$( sdcv -n --data-dir ~/dic/gujarati/ $url )" && exit ;;

 *) $option "$url" ;;
esac
