#!/bin/bash

#which clipboard to use, valid options are "primary" and "clipboard"
SELECTION=clipboard
#choose your terminal
TERM=sakura
shopt -s lastpipe

echo -e "w3m\nmpv\nMPV\nyoutube-dl\nYOUTUBE-DL\ntransmission\ncurl-download\ncurl-save\nwget-saveall" | /usr/bin/dmenu -b | read "option"

case "$option" in

w3m) $TERM -e w3m "$(xclip -o -selection $SELECTION)" ;;
mpv) $TERM -e w3mpv "$(xclip -o -selection $SELECTION)" ;;
MPV) $TERM -e mpv "$(xclip -o -selection $SELECTION)"  ;;
youtube-dl) $TERM -e w3ytdl "$(xclip -o -selection $SELECTION)" ;;
YOUTUBE-DL) $TERM -e youtube-dl "$(xclip -o -selection $SELECTION)" ;;
## download torrent using transmission-cli
transmission) $TERM -e transmission-remote-cli "$(xclip -o -selection $SELECTION)" ;;
## downlod with curl in current dir (home)
curl-download) $TERM -e curl -L -O --user-agent Mozilla/5.0 "$(xclip -o -selection $SELECTION)" ;;
## save page as curl.html in Downloads
curl-save) $TERM -e curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 "$(xclip -o -selection $SELECTION)" ;;
## save full page with wget, saved in Downloads
wget-saveall) $TERM -e wget --user-agent=Mozilla/5.0 --mirror -p --convert-links -P ~/Downloads "$(xclip -o -selection $SELECTION)" ;;
## use any other external program with !chromium or !firefox or ?firefox etc.
*) "$option" "$(xclip -o -selection $SELECTION)" ;;
esac
